apiVersion: apps/v1
kind: Deployment
metadata:
  name: dockerethbackend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dockerethbackend
  template:
    metadata:
      labels:
        app: dockerethbackend
    spec:
      containers:
        - name: backend
          image: chargaoshou/dockerethbackend:v4.9 # v3 for docker-ethereum and v4.9 for mongodb
          resources:
            limits:
              cpu: "250m" # 250 millicores
              memory: "500Mi"
          ports:
            - containerPort: 4000
          env:
            - name: MONGODB_URI
              value: mongodb://mongodb-service:27017
            - name: DB_NAME
              value: mydb
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: username
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: password
