apiVersion: apps/v1
kind: Deployment
metadata:
  name: dockerethganache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dockerethganache
  template:
    metadata:
      labels:
        app: dockerethganache
    spec:
      containers:
        - name: ganache
          image: chargaoshou/dockerethganache:latest
          resources:
            limits:
              cpu: "250m" # 250 millicores
              memory: "500Mi"
          ports:
            - containerPort: 8545
